#!/bin/bash

export LANG=en_US.UTF-8
export LC_CTYPE=zh_CN.UTF-8
export LC_COLLATE=zh_CN.UTF-8
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"

# Program run in background

xrdb -merge .Xresources & # Load resources

# Set up an icon tray
trayer --edge top --align right --SetDockType true --SetPartialStrut true \
 --expand true --width 12 --transparent true --tint 0x191970 --height 22 &

# xsetroot -solid midnightblue  # Set the background color<

xsetroot -cursor_name left_ptr & # set cursor

# syndaemon -i 2 -d &

fcitx &
# sogou-qimpanel &

if [ -x /usr/bin/nm-applet ] ; then
   nm-applet --sm-disable &
fi

goldendict &

alsa-tray &

xscreensaver -no-splash &   # 屏保

variety &

# Window manager
exec xmonad
