" An example for a vimrc file.
"
" Maintainer:	Bram Moolenaar <Bram@vim.org>
" Last change:	2011 Apr 15
"
" To use it, copy it to
"     for Unix and OS/2:  ~/.vimrc
"	      for Amiga:  s:.vimrc
"  for MS-DOS and Win32:  $VIM\_vimrc
"	    for OpenVMS:  sys$login:.vimrc

" When started as "evim", evim.vim will already have done these settings.
if v:progname =~? "evim"
  finish
endif

" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

if has("vms")
  set nobackup		" do not keep a backup file, use versions instead
else
  set backup		" keep a backup file
endif
set history=50		" keep 50 lines of command line history
set ruler		" show the cursor position all the time
set showcmd		" display incomplete commands
set incsearch		" do incremental searching

" For Win32 GUI: remove 't' flag from 'guioptions': no tearoff menu entries
" let &guioptions = substitute(&guioptions, "t", "", "g")

" Don't use Ex mode, use Q for formatting
map Q gq

" CTRL-U in insert mode deletes a lot.  Use CTRL-G u to first break undo,
" so that you can undo CTRL-U after inserting a line break.
inoremap <C-U> <C-G>u<C-U>

" In many terminal emulators the mouse works just fine, thus enable it.
if has('mouse')
  set mouse=a
endif

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

" Only do this part when compiled with support for autocommands.
if has("autocmd")

  " Enable file type detection.
  " Use the default filetype settings, so that mail gets 'tw' set to 72,
  " 'cindent' is on in C files, etc.
  " Also load indent files, to automatically do language-dependent indenting.
  filetype plugin indent on

  " Put these in an autocmd group, so that we can delete them easily.
  augroup vimrcEx
  au!

  " For all text files set 'textwidth' to 78 characters.
  autocmd FileType text setlocal textwidth=78

  " When editing a file, always jump to the last known cursor position.
  " Don't do it when the position is invalid or when inside an event handler
  " (happens when dropping a file on gvim).
  " Also don't do it when the mark is in the first line, that is the default
  " position when opening a file.
  autocmd BufReadPost *
    \ if line("'\"") > 1 && line("'\"") <= line("$") |
    \   exe "normal! g`\"" |
    \ endif

  augroup END

else

  set autoindent		" always set autoindenting on

endif " has("autocmd")

" Convenient command to see the difference between the current buffer and the
" file it was loaded from, thus the changes you made.
" Only define it when not defined already.
if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r ++edit # | 0d_ | diffthis
		  \ | wincmd p | diffthis
endif

"""""""""""""""""""""""""
" vundle 官方配置
""""""""""""""""""""""""

filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'altercation/vim-colors-solarized'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'
Plugin 'Lokaltog/powerline'
" Plugin 'Valloric/YouCompleteMe'
" Plugin 'Valloric/ListToggle'
" Plugin 'scrooloose/syntastic'

call vundle#end()
filetype plugin indent on

" powerline 设置
set laststatus=2 " Always show the statusline
set encoding=utf-8
set t_Co=256
let g:Powerline_symbols='fancy'

" vim-markdown 设置
" let g:vim_markdown_folding_disabled=1
" let g:vim_markdown_initial_foldlevel=2

" 星际译王
" nmap F :call Mydict()<CR>
" set keywordprg=sdcv

"""""""""""""""""""""""
" 基本设置
"""""""""""""""""""""""

" 主题
set background=dark
colorscheme solarized
" colorscheme desert
" 当前行高亮
set cursorline
" hi CursorLine cterm=NONE ctermbg=darkblue ctermfg=white
" hi CursorColumn cterm=NONE ctermbg=darkblue ctermfg=white

" 设置编码，以支持中文
set fileencodings-=latin1
set fileencodings+=gb18030,big5,latin1

" 调整缩进
" 改变 ">" 的平移单位
set shiftwidth=4
" 改变 "<Tab>" 键的缩进量
set softtabstop=4
" 把制表符转变为空格
set expandtab

" 排版
" 自动换行
set textwidth=78
" m: 按字符为单位分行
" M: 连接行时，不要插入空格
set formatoptions+=mM

" 储存状态信息
set viminfo+=!
